add_executable(BooksRead
    books_read.cpp
)

add_executable(MultiDimArrays
    multi_dimensional_arrays.cpp
)

add_executable(Tuple
    tuple.cpp
)

add_executable(SquareItemsChallenge
    square_items_challenge.cpp
)

add_executable(SearchArrays
    search_array.cpp
)

add_executable(Sorting
    sorting.cpp
)

add_executable(SecondSmallestItemChallenge
    second_smallest_item.cpp
)